storage:
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1

replication:
  replSetName: rs0

net:
  bindIpAll: true
  port: 27017

security:
  authorization: enabled
  keyFile: /etc/mongodb-keyfile
